### ISSUE TITLE
Roadmap correction on the login and register page

### ISSUE THREAD

**Issue by marchufschmitt** [InseeFrLab/onyxia-ui#215]
- [x] Hover status for login button
- [x] Resolve the problem with blue background error on the textfield
- [x] Add eye icon for the password textfield (text display or hide)
- [x] Feedback text or new screen when user forgot his password and click on the button (to be specified together which is better)
- [x] Send mail with keycode or new password (when user forgot his password)
- [x] Add text on register screen : « By clicking Agree & Join, you agree to the User Agreement and Privacy Policy of the datalab. »
- [x] Change text button on register screen : « Agree & register »
- [x] Add return button on register screen 
- [x] Add the differents help texts (username and password)
- [x] <del>Disabled submit button as long as a field isn’t completed<del> Incompatible with autofill
- [x] Add the differents error texts :
    - [x] Login : 
        - [x] Username or mail address invalid  
        - [x] Password invalid  
        - [x] <del>or Username, mail address or password invalid (to be specified together which is better)</del> There is a miss-understanding about what the responsibility of the the front is. We do not check if the username/password is a valid authentication, Keycloak does and gives a feedback via a error message if login was unsuccessful. We can only check if the username/email and password are well formed.
    - Register :
        - [x] Mail address format is invalid
        - [x] Username format is invalid
        - [x] Password doesn’t match
        - [x] <del>Email already exists.</del> can't do that on front
- [x] Reduce size of the logo on the register page background (80% of height - width: auto)
- [x] Center the dialog on the screen (of login and register page)
- [x] Add header on the register page  
- [x] Hitting enter doesn't validate form
- [x] Tab should skip username in register
- [x] Tab should skip "cancel" button in login.
- [x] Autofill options show again for password on Safari
- [x] Autocomplete suggestion appears before the form is visible on Safari
- [x] Click on logo should redirect to the community website.
- [x] Navigate back doesn't work
- [x] Cancel doesn't work

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/112947397-03eca000-9137-11eb-820a-8644929db3db.png)

![image](https://user-images.githubusercontent.com/6702424/112947446-17980680-9137-11eb-9cdc-dd9c723e3bda.png)

**Comment by garronej** [comment]
> * [ ]  Reduce size of the logo on the register page background (80% of height - width: auto)

@marchufschmitt are you sure about that? If I apply the rule:  

![image](https://user-images.githubusercontent.com/6702424/113482867-db4f0800-94a0-11eb-82b0-2b2614a1a16c.png)

Looks too small to me, smaller than in Figma for sure... I will go for 90% you tell me if it's ok.

![image](https://user-images.githubusercontent.com/6702424/113482912-13eee180-94a1-11eb-8b12-f05e6e19bbfb.png)

**Comment by garronej** [comment]
> * [ ]  Autocomplete thinks password is a username field on safari and chrome

This is what we want to avoid (only on Safari):
![image](https://user-images.githubusercontent.com/6702424/113485845-ef4e3600-94af-11eb-9ea5-a93ea59f13ee.png)
